export const defaults = {
  width: 'full',
  innerWidth: 'xl',
  innerBorderRadius: 'none',
  borderRadius: 'none',
  marginTop: 'none',
  marginBottom: 'none',
  paddingTop: 'm',
  paddingBottom: 'm',
  paddingLeft: 'm',
  paddingRight: 'm',
  backgroundColor: 'transparent',
  unwrapped: false,
  element: 'section',
  introContent: '',
  elementIntroContent: '',
  headingTextColor: '#000000',
  image: null,
  children: [],
} as const;
